
engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true

languages:
   Ruby: true
   
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.go"
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - d326692d582e65022fb00a5f80b5dd2f
    - 25843d970c93178e3d7523743d88481f
    - 12ff962ee1709ad46e5fc8e872c6456c


# ... CONFIG CONTENT ...
